# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b5b638b5764e57bdded8a3f7fd2ff16377cced3f93b5d0262ee1dce901d203d9662b225bd6ed6315eca7c64b2dfabe990c9fdf88dc97c73b947dcde4f3019fab

test:
  secret_key_base: e7431af96943b620f98dd96df082549246d53d0f9e921cf7ae96925a0db51933694934f3f86beb22f86f66f18f263cf618ecc10b4a8d8851c5a06c95611b150c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
