# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3fc0dddf89ca49ee3656c6247ad5314a1eda1b2b60e0cf5b6bdd9da7fc59ef70ebfc140b93505ec74c2ff95fa7165e7c26129fd9c09a08332e6dc7f9f6e49cbf

test:
  secret_key_base: 7c0325f2fa848db06fb90f4a936751ca886d7911731044ff5a381c8b03900097ba2f44df68939c92138f88ed4647a697030f5a8e4d3e4ffc46a46e61be66d74a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
