# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 28bfc0eca4e56e64a681ccda0b65467b5ed3312f8179dbab015ca1709d5f03d9096c26903d4928ae72f0ee6323122de8c3d0c989d35516362eddb76406024b01

test:
  secret_key_base: e330848fc91b10e46b608beb34dcb1d56d4807cc83021282e5edca80e52b43e654410f82b1923cf6e997c8f1309a5f9c223c5fd85675d4ae670c9b578e34664e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
